---

layout: page
lang: "en"
journal: "LIBREAS. Library Ideas"
issue: "27"
year: "2015"
contributor: 
- "Andreas Degkwitz"
title: "From Special Subject Collections to Discipline Driven Information Provisioning"
urn: "urn:nbn:de:kobv:11-100229847"
date: 2015-05-24 12:00
comments: false
sharing: true
footer: true

---