---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "27"
year: "2015"
contributor: 
- "Karsten Schuldt"
- "Rudolf Mumenthaler"
title: "Forschungsmethoden in die Praxisausbildung einbinden? Ansätze an der HTW Chur"
urn: "urn:nbn:de:kobv:11-100229836"
date: 2015-05-24 12:00
comments: false
sharing: true
footer: true

---