---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "27"
year: "2015"
contributor: 
- "Aylin Ilhan"
description: "Mit der Entwicklung 'smarter' und 'ubiquitärer' Städte und ihren an das
'Internet der Dinge' orientierten Informationsdiensten eröffnet sich der
informationswissenschaftlichen Forschung ein neues weites
Untersuchungsfeld. Anhand der ubiquitären Stadt New Songdo City in
Südkorea stellen wir Informationsbedarfs- und
Technologieakzeptanzuntersuchungen vor, die einen Einblick in die
Zufriedenheit der Nutzer mit diesen neuartigen Informationsdiensten
gestatten. Der Beitrag ist die Überarbeitete Version eines Vortrages,
den die Autorin im Rahmen des 5. Studenten-Workshops für
informationswissenschaftliche Forschung (SWiF 2014) am 14. 11. 2014 an
der Humboldt-Universität zu Berlin hielt.
"
title: "Evaluation ubiquitärer Informationsdienste in New Songdo City"
urn: "urn:nbn:de:kobv:11-100229888"
date: 2015-05-24 12:00
comments: false
sharing: true
footer: true

---