---

layout: page
lang: "en"
journal: "LIBREAS. Library Ideas"
issue: "27"
year: "2015"
contributor: 
- "Alison Peters"
title: "A Textbook for Infinite Learning. It’s a Small World, After All – Review of Sandra Hirsch [Ed.] (2015): Information Services Today: An Introduction. Lanham, MD: Rowman & Littlefield. 514 p., ISBN 978-1-4422-3957-9"
urn: "urn:nbn:de:kobv:11-100229865"
date: 2015-05-24 12:00
comments: false
sharing: true
footer: true

---