---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "27"
year: "2015"
contributor: 
- "Corinna Haas"
title: "Zwischen Participatory Design und lokaler Forschung. Ethnografie in drei neuen Methodenhandbüchern"
urn: "urn:nbn:de:kobv:11-100229826"
abstract: "Vor kurzem wurden drei neue Methoden-Handbücher für Bibliothekswissenschaftler veröffentlicht (Umlauf u.a., Hg. 2013; Siegfried u.a. 2013 und Schuldt 2014), die alle auf das Thema Ethnografie im Bibliotheksbereich eingehen. Mein Beitrag fragt danach, welches Potential sie jeweils in der Ethnografie sehen, und konfrontiert zwei Positionen: Erstens, Ethnografie sei primär geeignet, die Nutzerbeteiligung bei Designprozessen zu unterstützen (Umlauf und Siegfried). Und zweitens, Ethnografie sei ein möglicher Ansatz für lokale, sozialwissenschaftliche Forschung in und über Bibliotheken (Schuldt). Die Autorin vertritt die Position, dass partizipatives Design einen hervorragenden Ansatz für die Nutzerbeteiligung darstellt, sich das Potential ethnografischer Methoden für den Bibliotheksbereich darin jedoch nicht erschöpft. Vielmehr ist Ethnografie auch eine Methode für die kultur- und sozialwissenschaftliche Forschung in und über Bibliotheken, weshalb Karsten Schuldts Appell, in Bibliotheken lokal zu forschen, unbedingt Unterstützung verdient."
date: 2015-05-24 12:00
comments: false
sharing: true
footer: true

---