---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "27"
year: "2015"
contributor: 
- "Felix Hüppi"
title: "Interviews und Beobachtungen als Methodenkombination. Auch für Bibliotheken?"
urn: "urn:nbn:de:kobv:11-100229817"
date: 2015-05-24 12:00
comments: false
sharing: true
footer: true

---