---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "27"
year: "2015"
contributor: 
- "Christoph Szepanski"
title: "Ein Blick auf das Davor. Metatheorien am Beispiel der Activity Theory in der Informationsverhaltensforschung"
urn: "urn:nbn:de:kobv:11-100229855"
date: 2015-05-24 12:00
comments: false
sharing: true
footer: true

---