---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "27"
year: "2015"
contributor: 
- "Redaktion LIBREAS"
title: "Editorial #27: Methoden"
subtitle: ""
urn: " urn:nbn:de:kobv:11-100229809"
date: 2015-05-23 12:00
comments: false
sharing: true
footer: true

---